<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.JellyInspector</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.JellyInspector</AssemblyName>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>

    <Version>0.2.1.1</Version>
    <AssemblyVersion>0.2.1.1</AssemblyVersion>
    <FileVersion>0.2.1.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.8">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>

    <PackageReference Include="Jellyfin.Model" Version="10.11.8">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration\configPage.html" />

    <None Remove="Web\**\*" />
    <EmbeddedResource Include="Web\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JellyInspector.Scanner\JellyInspector.Scanner.csproj" />
  </ItemGroup>

</Project>
